server:
  port: 9000
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/explore?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: '123456'
  aop:
    proxy-target-class: true
security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/oauth/token
dataSourceVariable:
  useridColumnName: id
  usernameColumnName: email
  passwordColumnName: password
  isbannedColumnName: is_banned
  isdeletedColumnName: is_deleted
